import Navbar from "./components/navbar";
import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-black min-h-screen'>
        <div className="container mx-auto my-auto py-6">
          {/* <div className="grid grid-cols-3 gap-2"> */}
          {/* <div className="flex">
            <Navbar />
          </div> */}
          <div className="w-1/5"></div>
          <div>{children}</div>
          <div className="w-1/5"></div>
        </div>
      </body>
    </html>
  );
}
